import { useEffect, useState, type FormEvent } from 'react';
import { Pencil, Plus, Search, Trash2, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { listCustomers, removeCustomer, saveCustomer } from '../lib/firestore';
import type { Customer } from '../types';
import styles from './Pages.module.css';

export function Customers() {
  const { user } = useAuth(); const [customers, setCustomers] = useState<Customer[]>([]); const [form, setForm] = useState({ name: '', phone: '', address: '' }); const [editing, setEditing] = useState<string | null>(null); const [search, setSearch] = useState('');
  const load = () => user && listCustomers(user.uid).then(setCustomers); useEffect(() => { load(); }, [user]);
  const submit = async (e: FormEvent) => { e.preventDefault(); if (!user || !form.name.trim()) return; await saveCustomer(user.uid, { ...form, name: form.name.trim() }, editing || undefined); setForm({ name: '', phone: '', address: '' }); setEditing(null); load(); };
  const edit = (customer: Customer) => { setEditing(customer.id); setForm({ name: customer.name, phone: customer.phone, address: customer.address }); };
  const visible = customers.filter((c) => `${c.name} ${c.phone}`.toLowerCase().includes(search.toLowerCase()));
  return <><div className={styles.intro}><h2>Customers</h2><p>Customers are also created automatically when you save a bill.</p></div><section className={styles.split}><form className={`${styles.card} ${styles.inlineForm}`} onSubmit={submit}><h3>{editing ? 'Edit customer' : 'Add customer'}</h3><label>Name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Phone<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label>Address<textarea rows={3} value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></label><div className={styles.actions}><button className="primary-button"><Plus size={16}/>{editing ? 'Update customer' : 'Add customer'}</button>{editing && <button type="button" className="secondary-button" onClick={() => { setEditing(null); setForm({ name: '', phone: '', address: '' }); }}>Cancel</button>}</div></form><section className={styles.card}><div className={styles.tableTitle}><div><h3>Customer directory</h3><span>{customers.length} customers</span></div><label className="search-box"><Search size={16}/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name or phone" /></label></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Customer</th><th>Phone</th><th>Address</th><th></th></tr></thead><tbody>{visible.map((customer) => <tr key={customer.id}><td><Link className={styles.customerLink} to={`/customers/${customer.id}`}><UserRound size={16}/>{customer.name}</Link></td><td>{customer.phone || '-'}</td><td>{customer.address || '-'}</td><td className="row-actions"><button title="Edit customer" onClick={() => edit(customer)}><Pencil size={16}/></button><button title="Delete customer" onClick={async () => { if (window.confirm('Delete this customer?')) { await removeCustomer(customer.id); load(); } }}><Trash2 size={16}/></button></td></tr>)}{!visible.length && <tr><td colSpan={4} className="empty-cell">No customers found.</td></tr>}</tbody></table></div></section></section></>;
}
