import { useEffect, useMemo, useState } from 'react';
import { format, startOfMonth, startOfToday, subDays } from 'date-fns';
import { Area, AreaChart, CartesianGrid, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { FileText, IndianRupee, Package, Users } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { SlidingNumber } from '@/components/animate-ui/primitives/texts/sliding-number';
import { Globe } from '@/components/ui/globe';
import { listCustomers, listInvoices, listProducts } from '../lib/firestore';
import { currency } from '../lib/money';
import type { Invoice } from '../types';
import styles from './Dashboard.module.css';

const periods = ['7 Days', '30 Days', 'Year'] as const;
export function Dashboard() {
  const { user } = useAuth(); const [invoices, setInvoices] = useState<Invoice[]>([]); const [counts, setCounts] = useState({ customers: 0, products: 0 }); const [period, setPeriod] = useState<(typeof periods)[number]>('7 Days'); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!user) return; Promise.all([listInvoices(user.uid), listCustomers(user.uid), listProducts(user.uid)]).then(([bills, customers, products]) => { setInvoices(bills); setCounts({ customers: customers.length, products: products.length }); }).finally(() => setLoading(false)); }, [user]);
  const now = startOfToday(); const today = format(now, 'yyyy-MM-dd'); const month = startOfMonth(now);
  const kpis = useMemo(() => ({ today: invoices.filter((i) => i.date === today).reduce((sum, i) => sum + i.grandTotal, 0), month: invoices.filter((i) => new Date(`${i.date}T00:00:00`) >= month).reduce((sum, i) => sum + i.grandTotal, 0), turnover: invoices.reduce((sum, i) => sum + i.grandTotal, 0) }), [invoices, today, month]);
  const trend = useMemo(() => { const days = period === '7 Days' ? 7 : period === '30 Days' ? 30 : 365; const map = new Map<string, number>(); for (let i = days - 1; i >= 0; i--) map.set(format(subDays(now, i), period === 'Year' ? 'MMM yy' : 'dd MMM'), 0); invoices.forEach((bill) => { const d = new Date(`${bill.date}T00:00:00`); if (d >= subDays(now, days - 1)) { const key = format(d, period === 'Year' ? 'MMM yy' : 'dd MMM'); map.set(key, (map.get(key) || 0) + bill.grandTotal); } }); return [...map].map(([date, sales]) => ({ date, sales })); }, [invoices, now, period]);
  const products = useMemo(() => { const tally = new Map<string, number>(); invoices.forEach((bill) => bill.items.forEach((item) => tally.set(item.description || 'Unspecified', (tally.get(item.description || 'Unspecified') || 0) + item.amount))); return [...tally].sort((a, b) => b[1] - a[1]).slice(0, 5).map(([name, value]) => ({ name, value })); }, [invoices]);
  if (loading) return <div className="page-loader">Loading dashboard...</div>;
  const cards = [["Today's Sales", kpis.today, IndianRupee, true], ["This Month's Sales", kpis.month, IndianRupee, true], ['Overall Turnover', kpis.turnover, IndianRupee, true], ['Total Bills', invoices.length, FileText, false], ['Total Customers', counts.customers, Users, false], ['Total Products', counts.products, Package, false]] as const;
  return <><div className={styles.kpis}>{cards.map(([label, value, Icon, isCurrency]) => <section className={styles.kpi} key={label}><span><Icon size={20} /></span><div><p>{label}</p><strong>{isCurrency && '₹'}<SlidingNumber number={value} fromNumber={0} thousandSeparator="," /></strong></div></section>)}</div><section className={styles.grid}><div className={styles.chartCard}><div className={styles.cardHeader}><div><h2>Sales trends</h2><p>Invoice total by date</p></div><div className={styles.pills}>{periods.map((item) => <button key={item} onClick={() => setPeriod(item)} className={period === item ? styles.selected : ''}>{item}</button>)}</div></div><ResponsiveContainer width="100%" height={300}><AreaChart data={trend}><defs><linearGradient id="sales" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2f8fc2" stopOpacity={.3}/><stop offset="95%" stopColor="#2f8fc2" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{ fontSize: 11 }} interval={period === 'Year' ? 30 : 'preserveStartEnd'}/><YAxis tickFormatter={(v) => `₹${v}`} tick={{ fontSize: 11 }}/><Tooltip formatter={(v) => currency(Number(v))} /><Area type="monotone" dataKey="sales" stroke="#217bb0" strokeWidth={2.5} fill="url(#sales)"/></AreaChart></ResponsiveContainer></div><div className={styles.chartCard}><div className={styles.cardHeader}><div><h2>Top selling products</h2><p>By invoiced value</p></div></div>{products.length ? <ResponsiveContainer width="100%" height={300}><PieChart><Pie data={products} dataKey="value" nameKey="name" cx="50%" cy="47%" outerRadius={94} fill="#2f8fc2" label={({ name }) => name}/><Tooltip formatter={(v) => currency(Number(v))} /></PieChart></ResponsiveContainer> : <div className={styles.empty}>Your top products will appear after you save invoices.</div>}</div></section></>;
}
