import { ArrowRight, BarChart3, CheckCircle2, FileText, LockKeyhole, MousePointer2, Package, ReceiptText, ShieldCheck, Sparkles, UsersRound, Sun, Moon } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import styles from './Landing.module.css';

const plans = [{ name: 'Monthly', price: '₹499', period: '/ month', note: 'GST included' }, { name: '6 Months', price: '₹2,499', period: '/ 6 months', note: 'GST included' }, { name: 'Yearly', price: '₹3,499', period: '/ year', note: 'Usually ₹6,000 · GST included', featured: true }];

export function Landing() {
  const { user, isAdmin } = useAuth();
  const [theme, setTheme] = useState<'light' | 'dark'>('light');
  
  return <main className={`${styles.page} ${theme === 'dark' ? styles.dark : ''}`}>
    <nav className={styles.nav}><Link to="/" className={styles.brand}><img src="/logo.jpg" alt="Billora" className={styles.brandLogo} />Billora</Link><div className={styles.links}><a href="#home">Home</a><Link to="/demo">Demo</Link><a href="#why-billora">Why Billora</a><a href="#pricing">Pricing</a><a href="#contact">Contact</a></div><div className={styles.actions}><button onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')} className={styles.themeToggle}>{theme === 'light' ? <Moon size={18} /> : <Sun size={18} />}</button>{user ? <Link to={isAdmin ? "/admin" : "/subscription"} className={styles.start}>{isAdmin ? "Admin Console" : "Subscribe now"} <ArrowRight size={16}/></Link> : <><Link to="/login" className={styles.login}>Sign in</Link><Link to="/register" className={styles.start}>Start now <ArrowRight size={16}/></Link></>}</div></nav>
    <section id="home" className={styles.hero}><div className={styles.copy}><p><Sparkles size={15}/> Professional billing for growing shops</p><h1>Everything your shop needs to bill, track, and grow.</h1><span>Create clean invoices quickly, know your sales in real time, and build stronger customer relationships from one beautiful workspace.</span><div>{user ? <Link className={styles.cta} to={isAdmin ? "/admin" : "/subscription"}>{isAdmin ? "Open Admin Console" : "Subscribe to workspace"} <ArrowRight size={17}/></Link> : <Link className={styles.cta} to="/register">Create your workspace <ArrowRight size={17}/></Link>}<Link className={styles.secondary} to="/demo">See how it works</Link></div><small><ShieldCheck size={14}/> Secure records · No credit card data stored by Billora</small></div></section>
    <section className={styles.proof}><div><strong>Keyboard-first</strong><span>Fast invoice entry</span></div><div><strong>A4 + PDF</strong><span>Ready to print</span></div><div><strong>Customer history</strong><span>Every order organised</span></div><div><strong>Live reports</strong><span>Daily to yearly insight</span></div></section>
    <section id="about-us" className={styles.section} style={{ textAlign: 'center', maxWidth: 760, margin: '0 auto 80px' }}><div className={styles.sectionIntro}><p>About Us</p><h2>Empowering shop owners with smart tools.</h2><span>We built Billora because we noticed that local shops were stuck using either overly complicated legacy software or pen and paper. Our mission is to provide an incredibly fast, modern, and beautiful billing workspace that requires zero training to use. We believe your software should be a joy to use every single day.</span></div></section>
    <section id="why-billora" className={styles.why}><div className={styles.dashboardMock}><div className={styles.mockHead}><span/><span/><span/></div><div className={styles.mockStats}><i/><i/><i/></div><div className={styles.mockGraph}><b/><b/><b/><b/><b/><b/><b/></div><div className={styles.mockRows}><em/><em/><em/></div></div><div><p>Why choose us</p><h2>Built around the work you actually do at the counter.</h2><ul><li><MousePointer2 size={18}/><span><b>Speed without shortcuts</b>Keyboard flow moves through every invoice item field.</span></li><li><UsersRound size={18}/><span><b>Every customer remembered</b>View complete bill history, totals, average order, and top products.</span></li><li><FileText size={18}/><span><b>Records that stay clear</b>Search bills, update errors, print old invoices, and download PDFs any time.</span></li></ul></div></section>
    <section id="how-it-works" className={styles.section}><div className={styles.sectionIntro}><p>How it works</p><h2>From item to invoice in three calm, quick steps.</h2></div><div className={styles.steps}><article><span>01</span><Package size={25}/><h3>Add your products</h3><p>Save common products and rates once. Search them instantly whenever you create a bill.</p></article><article><span>02</span><ReceiptText size={25}/><h3>Create the invoice</h3><p>Search the customer, type items with Enter-key navigation, then see totals update live.</p></article><article><span>03</span><BarChart3 size={25}/><h3>Understand every sale</h3><p>Review daily, weekly, monthly, and yearly performance in clear dashboards and customer records.</p></article></div></section>
    <section id="pricing" className={styles.pricing}><div className={styles.sectionIntro}><p>Simple subscription</p><h2>Choose the access that fits your shop.</h2><span>Pay securely with Razorpay. Your workspace unlocks as soon as payment is verified.</span></div><div className={styles.planGrid}>{plans.map((plan) => <article className={plan.featured ? styles.featured : ''} key={plan.name}>{plan.featured && <b>Best value</b>}<h3>{plan.name}</h3><p><strong>{plan.price}</strong><span>{plan.period}</span></p><small>{plan.note}</small><Link to={user ? (isAdmin ? "/admin" : "/subscription") : "/register"}>Choose {plan.name} <ArrowRight size={15}/></Link><ul><li><CheckCircle2 size={15}/> Unlimited invoices</li><li><CheckCircle2 size={15}/> Products and customers</li><li><CheckCircle2 size={15}/> Analytics, printing, PDF</li></ul></article>)}</div></section>
    <section id="contact" className={styles.section} style={{ textAlign: 'center', maxWidth: 600, margin: '0 auto 80px' }}><div className={styles.sectionIntro}><p>Contact Us</p><h2>We're here to help</h2><span>Have questions about your billing setup? Reach out to us directly.</span></div><div className={styles.contactBlock}><strong>Email: thegopichand@gmail.com</strong><strong>Phone: +91 97055 27264</strong><span>Andhra Pradesh, India</span></div></section>
    <footer><div className={styles.brand}><img src="/logo.jpg" alt="Billora" className={styles.brandLogo} />Billora</div><p>Billing software designed for the daily rhythm of small shops.</p><Link to={user ? (isAdmin ? "/admin" : "/dashboard") : "/login"}>{user ? "Go to your workspace" : "Sign in to your workspace"}</Link></footer>
  </main>;
}
